export const reducerCases = {
  SET_TOKEN: "SET_TOKEN",
  SET_USER: "SET_USER",
  SET_NAV: "SET_NAV",
  SET_PLAYLISTS: "SET_PLAYLISTS",
  SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
  SET_PLAYLIST: "SET_PLAYLIST",
  SET_PLAYING: "SET_PLAYING",
  SET_PLAYER_STATE: "SET_PLAYER_STATE",
  NAV_SCROLL: "NAV_SCROLL",
  SET_HEADER: "SET_HEADER",
};
